/*
 * Copyright (c) 2016-2020 by Pavel Panfilov <firstlast2007@gmail.com> skype pav2000pav
 * &                       by Vadim Kulakov vad7@yahoo.com, vad711
 * "Народный контроллер" для тепловых насосов.
 * Данное програмноое обеспечение предназначено для управления 
 * различными типами тепловых насосов для отопления и ГВС.
 *
 * This file is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 */
// ------------------------------------------------------------------------------------------------------------------------
// Хранение минимальной веб морды в памяти контроллера, используется если отказ сд карты ----------------------------------
// ------------------------------------------------------------------------------------------------------------------------

#ifndef NoSDpage_h
#define NoSDpage_h

// Конвертор http://www.buildmystring.com/default.php
// индексная страница без карты
const char index_noSD[] =
"<html>\r\n"
"<head>\r\n"
"  <title>Народный контроллер ТН</title>\r\n"
" <meta charset=\"utf-8\" />\r\n"
" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
" <script type='text/javascript'>\r\n"
"function updateParam(paramids)\r\n"
"{\r\n"
" setInterval(function() {loadParam(paramids)}, 5000); // время обновления параметров в в миллисекундах\r\n"
" loadParam(paramids);\r\n"
"}\r\n"
"\r\n"
"function setParam(paramid, resultid)\r\n"
"{\r\n"
"var elid = paramid.replace(/\\(/g,\"-\").replace(/\\)/g,\"\").toLowerCase();\r\n"
"var rec = new RegExp('et_listChart');\r\n"
"var res = new RegExp('et_freon|et_rule|et_testMode|et_FC|et_EEV|et_modeHP');\r\n"
"var ret = new RegExp('[(]SCHEDULER[)]');\r\n"
"var rer = new RegExp('MESS_RESET|MESS_WARNING|MESS_SD|MESS_TEMP|MESS_LIFE|MESS_ERROR|[(]MAIL[)]|MAIL_AUTH|MAIL_INFO|[(]SMS[)]|et_Relay|UPDATE_I2C|et_oHP[(]SAVE_ON|Boiler[(]BOILER_ON|Boiler[(]SCHEDULER_ON|Boiler[(]ADD_HEATING|Boiler[(]SALLMONELA|et_Network[(]DHCP|et_Network[(]PASSWORD|et_oHP[(]ADD_HEAT|RESET_HEAT|CIRCULATION|et_oHP[(]HIST|et_oHP[(]BEEP|RTV_OFF|et_oHP[(]NEXTION|et_oHP[(]EEV_CLOSE|get_datetime[(]UPDATE');\r\n"
"if (rer.test(paramid)) { swichid = document.getElementById(elid); if (swichid.checked) { elval =1; } else { elval = 0; } }\r\n"
"else if (ret.test(paramid)) {\r\n"
"             var divscheduler = document.getElementById(\"get_boiler-scheduler\");           \r\n"
"             var inputs = divscheduler.getElementsByTagName(\"input\");\r\n"
"             var elval = \"\";\r\n"
"             for (var i = 1; i < inputs.length; i++){\r\n"
"               if (inputs[i-1].checked){ elval += 1; } else { elval += 0; }\r\n"
"               if ( i % 24 == 0) {elval +=\"/\";}\r\n"
"             }\r\n"
" }\r\n"
"else { var elval = document.getElementById(elid).value;}\r\n"
"if (res.test(paramid)) {var elsend = paramid.replace(/get_/g,\"set_\").replace(/\\)/g,\"\") + \"(\" + elval +\")\";}\r\n"
"else if(rec.test(paramid)) { var elsend = paramid.replace(/get_listChart/g,\"get_Chart(\"+elval+\")\"); }\r\n"
"else {var elsend = paramid.replace(/get_/g,\"set_\").replace(/\\)/g,\"\") + \"=\" + elval +\")\";}\r\n"
"if(resultid == \"\" || resultid == null )  {\r\n"
" var valueid = paramid.replace(/set_/g,\"get_\").replace(/\\(/g,\"-\").replace(/\\)/g,\"\").toLowerCase();\r\n"
"} else {\r\n"
" var valueid = resultid;\r\n"
"}\r\n"
"if(!rec.test(paramid)) { document.getElementById(valueid).value = \"\"; document.getElementById(valueid).placeholder  = \"\"; }\r\n"
"loadParam(elsend, true, valueid); \r\n"
"}\r\n"
"\r\n"
"function loadParam(paramid, noretry, resultdiv)\r\n"
"{\r\n"
"var check_ready = 1;\r\n"
"var queue = 0;\r\n"
"var req_stek = new Array();\r\n"
"  if (queue == 0)\r\n"
"  {\r\n"
" req_stek.push(paramid);\r\n"
"  }\r\n"
"  else if (queue == 1)\r\n"
"  {\r\n"
" req_stek.unshift(paramid);\r\n"
" queue = 0;\r\n"
"  }\r\n"
"  \r\n"
"  if (check_ready == 1)\r\n"
"  { unique(req_stek);\r\n"
" var oneparamid = req_stek.shift();\r\n"
" check_ready = 0;\r\n"
"   \r\n"
"var request = new XMLHttpRequest(); \r\n"
"var findz = new RegExp('/,/gi');\r\n"
"//if (oneparamid.search(findz) != -1 )  { \r\n"
" var reqstr = oneparamid.replace(/,/g,'&'); \r\n"
" // } else { var reqstr = oneparamid; } \r\n"
"\r\n"
"request.open(\"GET\", \"/&\" + reqstr + \"&&\", true); // адрес и порт контроллера"
"request.timeout = 4000; // таймаут ожидание ответа от контроллера. Чем хуже интертнет, тем выше значения. Но не более времени обновления параметров\r\n"
"request.send (null);\r\n"
"request.onreadystatechange = function()\r\n"
" {\r\n"
" if (this.readyState != 4) return;\r\n"
"   if (request.status == 200)\r\n"
"   { \r\n"
"     if (request.responseText != null)\r\n"
"     {\r\n"
"       var arr = request.responseText.replace(/^\x7f+/, '').replace(/\x7f\x7f*$/, '').split('\x7f');\r\n"
"       if (arr != null && arr != 0  ) {\r\n"
"         check_ready = 1; // ответ получен, можно слать следующий запрос.\r\n"
"         if (req_stek.length != 0) // если массив запросов не пуст - заправшиваем следующие значения.\r\n"
"         {\r\n"
"           queue = 1;\r\n"
"           setTimeout(function() { loadParam(req_stek.shift()); }, 10); // запрашиваем следующую порцию.\r\n"
"         }         \r\n"
"       for (var i = 0; i < arr.length; i++) {\r\n"
"         if (arr[i] != null && arr[i] != 0) {\r\n"
"           var reerr = new RegExp('^E');\r\n"
"           var rec = new RegExp('^CONST|get_sysInfo|get_socketInfo');\r\n"
"           var reo = new RegExp('^scan_');\r\n"
"           var rer = new RegExp('^get_Relay|MESS_RESET|MESS_WARNING|MESS_SD|MESS_TEMP|MESS_LIFE|MESS_ERROR|[(]MAIL[)]|MAIL_AUTH|MAIL_INFO|[(]SMS[)]|UPDATE_I2C|Boiler[(]BOILER_ON|Boiler[(]SCHEDULER_ON|Boiler[(]ADDH|CIRC|RESH|Boiler[(]SALLMONELA|et_Network[(]DHCP|et_Network[(]PASSWORD|et_oHP[(]ADD_HEA|et_oHP[(]BEEP|RTV_OFF|get_oHP[(]SAVE_ON|et_oHP[(]NEXTION|et_oHP[(]HIST|et_oHP[(]EEV_CLOSE|get_datetime[(]UPDATE|oHP[(]WSPIF');\r\n"
"           var rep = new RegExp('^get_is');\r\n"
"           var ret = new RegExp('[(]SCHEDULER[)]');\r\n"
"           var res = new RegExp('et_Network[(]SIZE_PACKET|et_freon|et_rule|et_testMode|et_listChart|HP[(]RULE|HP[(]TARGET|SOCKET|W5200|et_modeHP|TIME_CHART');\r\n"
"           var rev = new RegExp(/\\([a-z0-9_]+\\)/i);\r\n"
"           var reg = new RegExp('^get_Chart');\r\n"
"           var remintemp = new RegExp('^get_mintemp');\r\n"
"           var remaxtemp = new RegExp('^get_maxtemp');\r\n"
"           if (rec.test(arr[i])) { var type = \"const\"; }\r\n"
"           else if (res.test(arr[i])) { var type = \"select\";  }  // значения\r\n"
"           else if (reg.test(arr[i])) { var type = \"chart\";  }  // график\r\n"
"           else if (ret.test(arr[i])) { var type = \"scheduler\";  }  // расписание\r\n"
"           else if (reo.test(arr[i])) { var type = \"scan\";  } // ответ на сканирование\r\n"
"           else if (rep.test(arr[i])) { var type = \"present\";  } // наличие датчика в конфигурации\r\n"
"           else if (rer.test(arr[i])) { var type = \"checkbox\";  }  // чекбокс\r\n"
"           else if (rev.test(arr[i])) { var type = \"values\";  }  // значения\r\n"
"           else { var type = \"str\"; }\r\n"
"           values = arr[i].split('=');\r\n"
"           if(type == 'scheduler') {\r\n"
"             var divscheduler = document.getElementById(\"get_boiler-scheduler\");           \r\n"
"             var inputs = divscheduler.getElementsByTagName(\"input\");\r\n"
"             cont1 = values[1].replace(/\\//g,\"\");\r\n"
"             for (var i = 0; i < inputs.length; i++){\r\n"
"               if (cont1.charAt(i) == 1){ inputs[i].checked = true; } else { inputs[i].checked = false; }\r\n"
"             }\r\n"
"           } else if(type == 'chart') {\r\n"
"             if (values[0] != null && values[0] != 0 && values[1] != null && values[1] != 0) { \r\n"
"               title = values[0].replace(/get_Chart\\(/g,\"\").replace(/\\)[0-9]?/g,\"\");\r\n"
"               var yizm = ''; var ytooltip = ''; var timeval = '';\r\n"
"               var regexpt = /^(T|O|d)/g;var regexpp = /^P/g;var regexpe = /^pos/g;var regexpr = /^R/g;\r\n"
"                 if(regexpt.test(title)) { yizm = \"Температура, °C\"; ytooltip = \" °C\"; }\r\n"
"\r\n"
"                 if(regexpr.test(title)) { yizm = \"Состояние реле\"; ytooltip = \"\"; }\r\n"
"                 if(regexpe.test(title)) { yizm = \"Позиция, шаги\"; ytooltip = \" шаг\";  }\r\n"
"               data = values[1].split(';'); var dataSeries = []; for (var i = 0; i < data.length - 1; i++) { dataSeries.push([[i], Number(data[i])]); }\r\n"
"               $('#'+resultdiv).highcharts({\r\n"
"                 title: {text: title ,x: -15 },\r\n"
"\r\n"
"                 yAxis: { title: { text: yizm }, allowDecimals: false,  plotLines: [{  value: 0,  width: 1,  color: '#808080'  }] },\r\n"
"                 tooltip: {valueSuffix: ytooltip },\r\n"
"                 legend: { layout: 'vertical',  align: 'right', verticalAlign: 'middle', borderWidth: 0 },\r\n"
"                 plotOptions: { series: { dataGrouping: { enabled: false } } },\r\n"
"                 series: [{ name: ' ', tooltip: { valueDecimals: 2 }, states: { hover: { enabled: false }}, showInLegend: false, turboThreshold: 0, data:  dataSeries, dashStyle: \"Solid\" }] });\r\n"
"             }  \r\n"
"           } else if (type == 'scan') {\r\n"
"               if (values[0] != null && values[0] != 0 && values[1] != null && values[1] != 0) {\r\n"
"                 cont1 = values[1].replace(/\\:/g,\"</td><td>\");\r\n"
"                 cont2 = cont1.replace(/(\\;)/g,\"</td></tr><tr><td>\");\r\n"
"                 var content = \"<tr><td>\" + cont2 + \"</td></tr>\";\r\n"
"                 document.getElementById(values[0].toLowerCase()).innerHTML = content;\r\n"
"                 cont3 = values[1].replace(/[0-9]:.{1,10}:[-0-9\\.]{1,5}:/g,\"\"); cont3 = cont3.replace(/;$/g,\"\");\r\n"
"                 var cont4 = cont3.split(';');           \r\n"
"                 for (var j=0;j<14;j++) {\r\n"
"                   document.getElementsByTagName('select')[j].options.length = 0;\r\n"
"                   optdef = new Option(\"---\", \"\", true, true);\r\n"
"                   document.getElementsByTagName('select')[j].add(optdef,null);\r\n"
"                   optres = new Option(\"reset\", 0, false, false);\r\n"
"                   document.getElementsByTagName('select')[j].add(optres,null);\r\n"
"                   for (var i=0,len=cont4.length;i<len;i++) {\r\n"
"                     opt = new Option(i+1, i+1, false, false);\r\n"
"                     document.getElementsByTagName('select')[j].add(opt,null);\r\n"
"                   }\r\n"
"                 }\r\n"
"               }\r\n"
"           } else if (type == 'select') { \r\n"
"               if (values[0] != null && values[0] != 0 && values[1] != null && values[1] != 0) {\r\n"
"                var idsel = values[0].toLowerCase().replace(/set_/g,\"get_\").replace(/\\([0-9]\\)/g,\"\").replace(/\\(/g,\"-\").replace(/\\)/g,\"\");\r\n"
"                if (idsel==\"get_testmode\") {\r\n"
"                 var element2=document.getElementById(\"get_testmode2\");\r\n"
"                 if(element2) {\r\n"
"                   var cont1 = values[1].split(';');\r\n"
"                   for (var n=0,len=cont1.length-1;n<len;n++) { \r\n"
"                       cont2 = cont1[n].split(':');\r\n"
"                       if (cont2[1] == 1)  {\r\n"
"                         if (cont2[0] != \"NORMAL\") {document.getElementById(\"get_testmode2\").className = \"red\";}\r\n"
"                         else {document.getElementById(\"get_testmode2\").className = \"\";}\r\n"
"                         document.getElementById(\"get_testmode2\").innerHTML = cont2[0];\r\n"
"                         } \r\n"
"                     }\r\n"
"                   }\r\n"
"                 }\r\n"
"                else if (idsel==\"get_ruleeev\") {\r\n"
"                 document.getElementById(\"get_freoneev\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-m_step\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-m_step2\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-correction\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-correction2\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-t_owerheat\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-t_owerheat2\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-time_in\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-time_in2\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-k_pro\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-k_pro2\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-k_in\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-k_in2\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-k_dif\").disabled = false;\r\n"
"                 document.getElementById(\"get_peev-k_dif2\").disabled = false;\r\n"
"                 }\r\n"
"                 else if (idsel==\"get_message-smtp_server\") {\r\n"
"                   loadParam(\"get_Message(SMTP_IP),get_Message(SMS_IP)\");\r\n"
"                 }   \r\n"
"                 else if (idsel==\"get_message-sms_service\") {\r\n"
"                   loadParam(\"get_Message(SMS_NAMEP1),get_Message(SMS_NAMEP2),get_Message(SMS_IP)\");\r\n"
"                 }   \r\n"
"                 var element=document.getElementById(idsel);\r\n"
"                 if(element) {document.getElementById(idsel).innerHTML=\"\";}\r\n"
"                 var element3 = document.getElementById(idsel);\r\n"
"                 if ( element3 && element3.tagName != \"SPAN\") {\r\n"
"                 var cont1 = values[1].split(';');\r\n"
"                 for (var k=0,len=cont1.length-1;k<len;k++) {\r\n"
"                   cont2 = cont1[k].split(':');\r\n"
"                   if (cont2[1] == 1)  {\r\n"
"                     selected = true;\r\n"
"                     \r\n"
"                     if (idsel==\"get_ruleeev\") {\r\n"
"                     if (k==0) {\r\n"
"                     document.getElementById(\"get_freoneev\").disabled = true;\r\n"
"                     document.getElementById(\"get_peev-m_step\").disabled = true;\r\n"
"                     document.getElementById(\"get_peev-m_step2\").disabled = true;                      \r\n"
"                     }\r\n"
"                     else if (k==1){\r\n"
"                     document.getElementById(\"get_peev-m_step\").disabled = true;\r\n"
"                     document.getElementById(\"get_peev-m_step2\").disabled = true;\r\n"
"                     }\r\n"
"                     else if (k==2 || k==3){\r\n"
"                     document.getElementById(\"get_peev-t_owerheat\").disabled = true;\r\n"
"                     document.getElementById(\"get_peev-t_owerheat2\").disabled = true;\r\n"
"                     document.getElementById(\"get_peev-k_pro\").disabled = true;\r\n"
"                     document.getElementById(\"get_peev-k_pro2\").disabled = true;\r\n"
"                     document.getElementById(\"get_peev-k_in\").disabled = true;\r\n"
"                     document.getElementById(\"get_peev-k_in2\").disabled = true;\r\n"
"                     document.getElementById(\"get_peev-k_dif\").disabled = true;\r\n"
"                     document.getElementById(\"get_peev-k_dif2\").disabled = true;\r\n"
"                     document.getElementById(\"get_freoneev\").disabled = true;\r\n"
"                     document.getElementById(\"get_peev-correction\").disabled = true;\r\n"
"                     document.getElementById(\"get_peev-correction2\").disabled = true;\r\n"
"                     }\r\n"
"                     if(k==2){\r\n"
"                       document.getElementById(\"get_peev-m_step\").disabled = true;\r\n"
"                       document.getElementById(\"get_peev-m_step2\").disabled = true;\r\n"
"                     }\r\n"
"                     } else if (idsel==\"get_cool-rule\") {\r\n"
"                       document.getElementById(\"get_cool-target\").disabled = false;document.getElementById(\"get_cool-dtemp\").disabled = false; document.getElementById(\"get_cool-hp_pro\").disabled = false; document.getElementById(\"get_cool-hp_in\").disabled = false; document.getElementById(\"get_cool-hp_dif\").disabled = false; document.getElementById(\"get_cool-hp_time\").disabled = false;\r\n"
"                           if (k==2) { document.getElementById(\"get_cool-target\").disabled = true;\r\n"
"                        } else if (k==1){ document.getElementById(\"get_cool-dtemp\").disabled = true; \r\n"
"                        } else if (k==0){ document.getElementById(\"get_cool-hp_time\").disabled = true; document.getElementById(\"get_cool-hp_pro\").disabled = true; document.getElementById(\"get_cool-hp_in\").disabled = true; document.getElementById(\"get_cool-hp_dif\").disabled = true; }\r\n"
"                     } else if (idsel==\"get_heat-rule\") {\r\n"
"                       document.getElementById(\"get_heat-target\").disabled = false; document.getElementById(\"get_heat-dtemp\").disabled = false; document.getElementById(\"get_heat-hp_pro\").disabled = false; document.getElementById(\"get_heat-hp_in\").disabled = false; document.getElementById(\"get_heat-hp_dif\").disabled = false; document.getElementById(\"get_heat-hp_time\").disabled = false;\r\n"
"                           if (k==2) { document.getElementById(\"get_heat-target\").disabled = true;\r\n"
"                        } else if (k==1){ document.getElementById(\"get_heat-dtemp\").disabled = true;\r\n"
"                        } else if (k==0){ document.getElementById(\"get_heat-hp_time\").disabled = true; document.getElementById(\"get_heat-hp_pro\").disabled = true; document.getElementById(\"get_heat-hp_in\").disabled = true; document.getElementById(\"get_heat-hp_dif\").disabled = true; }\r\n"
"                     } else if (idsel==\"get_cool-target\") {\r\n"
"                       if (k==0) { document.getElementById(\"get_cool-temp2\").disabled = true; document.getElementById(\"get_cool-temp1\").disabled = false;\r\n"
"                       } else if (k==1) { document.getElementById(\"get_cool-temp2\").disabled = false; document.getElementById(\"get_cool-temp1\").disabled = true;}\r\n"
"                     } else if (idsel==\"get_heat-target\") {\r\n"
"                       if (k==0) { document.getElementById(\"get_heat-temp2\").disabled = true; document.getElementById(\"get_heat-temp1\").disabled = false;                                            \r\n"
"                       } else if (k==1) { document.getElementById(\"get_heat-temp2\").disabled = false; document.getElementById(\"get_heat-temp1\").disabled = true;}\r\n"
"                     } \r\n"
"                     \r\n"
"                   } else { selected = false; }\r\n"
"                   if(idsel==\"get_listchart\") {      \r\n"
"                       for (var j=0;j<5;j++) {\r\n"
"                       opt = new Option(cont2[0], \"_\"+cont2[0], false, selected );\r\n"
"                       document.getElementsByTagName('select')[j].add(opt,null);\r\n"
"                       }\r\n"
"                     } else {\r\n"
"                       var opt = new Option(cont2[0], k, false, selected ); document.getElementById(idsel).add(opt,null);  \r\n"
"                     }\r\n"
"                   }\r\n"
"                 }\r\n"
"               }   \r\n"
"           } else if (type == 'const') {\r\n"
"               if (values[0] != null && values[0] != 0 && values[1] != null && values[1] != 0) {\r\n"
"                 cont1 = values[1].replace(/\\|/g,\"</td><td>\");\r\n"
"                 cont2 = cont1.replace(/(\\;)/g,\"</td></tr><tr><td>\");\r\n"
"                 var content = \"<tr><td>\" + cont2 + \"</td></tr>\";\r\n"
"                 document.getElementById(values[0].toLowerCase()).innerHTML = content; \r\n"
"               }\r\n"
"           } else if (type == 'values') {\r\n"
"               var valueid = values[0].replace(/set_/g,\"get_\").replace(/\\([0-9]*\\)/g,\"\").replace(/\\(/g,\"-\").replace(/\\)/g,\"\").toLowerCase(); //.toLowerCase().replace(/set_/g,\"get_\").replace(/\\([0-9]\\)/g,\"\");\r\n"
"               var valuevar = values[1].toLowerCase().replace(/[^\\w\\d]/g,\"\"); \r\n"
"               if (valueid != null  && valueid != \"\"  && values[1] != null) {\r\n"
"               if ( valueid == \"get_message-sms_ret\") {  \r\n"
"                   if(valuevar == \"waitresponse\") {  setTimeout(loadParam('get_Message(SMS_RET)'), 3000); } else { alert(values[1]); }\r\n"
"                 }               \r\n"
"               if ( valueid == \"get_message-mail_ret\") {  \r\n"
"                   if(valuevar == \"waitresponse\") {  setTimeout(loadParam('get_Message(MAIL_RET)'), 3000); } else { alert(values[1]); }\r\n"
"                 } \r\n"
"                 \r\n"
"                 element3=document.getElementById(valueid+\"3\");  if(element3)  {element3.value  = values[1];  element3.innerHTML = values[1];}\r\n"
"                 element=document.getElementById(valueid);\r\n"
"                 if(element) {if(element!=document.activeElement) {element.value = values[1]; element.innerHTML = values[1];}}\r\n"
"                 if(reerr.test(values[1]))   { element=document.getElementById(valueid); if(element) {element.placeholder = values[1];} } }  \r\n"
"                               \r\n"
"                 if(remintemp.test(valueid)) { document.getElementById(valueid.replace(/get_min/g,\"get_test\")).min = values[1]; }\r\n"
"                 else if (remaxtemp.test(valueid)) { document.getElementById(valueid.replace(/get_max/g,\"get_test\")).max = values[1]; }  \r\n"
"               \r\n"
"                 \r\n"
"                  \r\n"
"           } else if (type == 'present') {\r\n"
"               var valueid = values[0].replace(/\\(/g,\"-\").replace(/\\)/g,\"\").toLowerCase();\r\n"
"               if (valueid != null  && values[1] != null && values[1] == 0 ) {\r\n"
"                 element=document.getElementById(valueid);if(element) {element.className = \"inactive\";}\r\n"
"                 if(values[0] == \"get_isRelay(RHEAT)\" && values[1] == 0) {element=document.getElementById(\"get_ohp-add_heat\");if(element) {element.disabled = true;}}\r\n"
"                 if(values[0] == \"get_isRelay(REVI)\" && values[1] == 0) {element=document.getElementById(\"get_ohp-temp_evi\");if(element) {element.disabled = true;} element=document.getElementById(\"get_ohp-temp_evi2\");if(element) {element.disabled = true;}}\r\n"
"                 var tableElem = document.getElementById(valueid);\r\n"
"                 if (tableElem) {\r\n"
"                   var elements = tableElem.getElementsByTagName('select');\r\n"
"                   if(elements[0]) {elements[0].disabled = true;}\r\n"
"                 }\r\n"
"               }\r\n"
"           } else if (type == 'checkbox') {\r\n"
"               var valueid = values[0].replace(/\\(/g,\"-\").replace(/\\)/g,\"\").replace(/set_/g,\"get_\").toLowerCase();\r\n"
"                   if(values[1] == 1) {\r\n"
"                     document.getElementById(valueid).checked = true;\r\n"
"                     document.getElementById(valueid).innerHTML= \"вкл.\";\r\n"
"                   } else if (values[1] == 0) {\r\n"
"                     document.getElementById(valueid).checked = false;\r\n"
"                     document.getElementById(valueid).innerHTML= \"выкл.\";\r\n"
"                   }             \r\n"
"           } else {\r\n"
"               if (values[0] == \"get_WORK\" &&  values[1] == \"ON\" ) {\r\n"
"                 var element=document.getElementById(\"onoffswitch\");\r\n"
"                 var element2=document.getElementById(\"get_work2\");\r\n"
"                 if(element2) {document.getElementById(\"get_work2\").innerHTML = \"ON\";}\r\n"
"                 if(!element) {document.getElementById(values[0].toLowerCase()).innerHTML = \"ON\";}\r\n"
"                 else {document.getElementById(\"onoffswitch\").checked = true;}\r\n"
"                   if(document.getElementById('get_relay-rcomp')) document.getElementById('get_relay-rcomp').disabled = true;\r\n"
"                   if(document.getElementById('get_relay-rpumpi')) document.getElementById('get_relay-rpumpi').disabled = true;\r\n"
"                   if(document.getElementById('get_relay-rpumpo')) document.getElementById('get_relay-rpumpo').disabled = true;\r\n"
"                   if(document.getElementById('get_relay-rboiler')) document.getElementById('get_relay-rboiler').disabled = true;\r\n"
"                   if(document.getElementById('get_relay-rheat')) document.getElementById('get_relay-rheat').disabled = true;\r\n"
"                   if(document.getElementById('get_relay-rtrv')) document.getElementById('get_relay-rtrv').disabled = true;\r\n"
"                   if(document.getElementById('get_relay-rfan1')) document.getElementById('get_relay-rfan1').disabled = true;\r\n"
"                   if(document.getElementById('get_relay-rfan2')) document.getElementById('get_relay-rfan2').disabled = true;\r\n"
"                   if(document.getElementById('get_relay-r3way')) document.getElementById('get_relay-r3way').disabled = true;\r\n"
"                   if(document.getElementById('get_relay-revi')) document.getElementById('get_relay-revi').disabled = true;\r\n"
"                   if(document.getElementById('get_eev')) document.getElementById('get_eev').disabled = true;\r\n"
"                   if(document.getElementById('get_fc')) document.getElementById('get_fc').disabled = true;\r\n"
"                   if(document.getElementById('get_fc2')) document.getElementById('get_eev2').disabled = true;\r\n"
"                   if(document.getElementById('get_fc2')) document.getElementById('get_fc2').disabled = true;    \r\n"
"                   if(document.getElementById('get_testmode')) document.getElementById('get_testmode').disabled = true;  \r\n"
"                   if(document.getElementById('get_modehp')) document.getElementById('get_modehp').disabled = true;            \r\n"
"               } else if ( values[0] == \"get_WORK\" &&  values[1] == \"OFF\" ) {\r\n"
"                 var element=document.getElementById(\"onoffswitch\");\r\n"
"                 var element2=document.getElementById(\"get_work2\");\r\n"
"                 if(element2) {document.getElementById(\"get_work2\").innerHTML = \"OFF\";}\r\n"
"                 /*if(!element) {document.getElementById(values[0].toLowerCase()).innerHTML = \"OFF\";}*/\r\n"
"                 else {document.getElementById(\"onoffswitch\").checked = false;\r\n"
"                   }\r\n"
"                   \r\n"
"                   if(document.getElementById('get_relay-rcomp')) document.getElementById('get_relay-rcomp').disabled = false;\r\n"
"                   if(document.getElementById('get_relay-rpumpi')) document.getElementById('get_relay-rpumpi').disabled = false;\r\n"
"                   if(document.getElementById('get_relay-rpumpo')) document.getElementById('get_relay-rpumpo').disabled = false;\r\n"
"                   if(document.getElementById('get_relay-rboiler')) document.getElementById('get_relay-rboiler').disabled = false;\r\n"
"                   if(document.getElementById('get_relay-rheat')) document.getElementById('get_relay-rheat').disabled = false;\r\n"
"                   if(document.getElementById('get_relay-rtrv')) document.getElementById('get_relay-rtrv').disabled = false;\r\n"
"                   if(document.getElementById('get_relay-rfan1')) document.getElementById('get_relay-rfan1').disabled = false;\r\n"
"                   if(document.getElementById('get_relay-rfan2')) document.getElementById('get_relay-rfan2').disabled = false;\r\n"
"                   if(document.getElementById('get_relay-r3way')) document.getElementById('get_relay-r3way').disabled = false;\r\n"
"                   if(document.getElementById('get_relay-revi')) document.getElementById('get_relay-revi').disabled = false;\r\n"
"                   if(document.getElementById('get_eev')) document.getElementById('get_eev').disabled = false;\r\n"
"                   if(document.getElementById('get_fc')) document.getElementById('get_fc').disabled = false;\r\n"
"                   if(document.getElementById('get_fc2')) document.getElementById('get_eev2').disabled = false;\r\n"
"                   if(document.getElementById('get_fc2')) document.getElementById('get_fc2').disabled = false; \r\n"
"                   if(document.getElementById('get_testmode')) document.getElementById('get_testmode').disabled = false; \r\n"
"                   if(document.getElementById('get_modehp')) document.getElementById('get_modehp').disabled = false;\r\n"
"               } else if ( values[0] == \"get_uptime\") {\r\n"
"               var element1=document.getElementById(\"get_uptime\");\r\n"
"               var element2=document.getElementById(\"get_uptime2\");\r\n"
"               if(element1) {document.getElementById(\"get_uptime\").innerHTML =  values[1] ;} \r\n"
"               if(element2) {document.getElementById(\"get_uptime2\").innerHTML =  values[1] ;}                   \r\n"
"               } else if ( values[0] == \"get_EEV\") {\r\n"
"               var element1=document.getElementById(\"get_eev\");\r\n"
"               var element2=document.getElementById(\"get_eev2\");\r\n"
"               if(element1) {document.getElementById(\"get_eev\").innerHTML =  values[1];} \r\n"
"               if(element2) {document.getElementById(\"get_eev2\").innerHTML =  values[1];}                   \r\n"
"               } else if ( values[0] == \"set_EEV\") {\r\n"
"               var element1=document.getElementById(\"get_eev\");\r\n"
"               var element2=document.getElementById(\"get_eev2\");\r\n"
"               if(element1) {document.getElementById(\"get_eev\").innerHTML =  values[1];} \r\n"
"               if(element2) {document.getElementById(\"get_eev2\").innerHTML =  values[1];}                   \r\n"
"               } else if ( values[0] == \"get_errcode\" &&  values[1] == 0 ) {\r\n"
"                 document.getElementById(\"get_errcode\").innerHTML = \"OK\";\r\n"
"                 document.getElementById(\"get_error\").innerHTML = \"\";\r\n"
"               } else if (values[0] == \"get_errcode\" &&  values[1] < 0) {\r\n"
"                 document.getElementById(\"get_errcode\").innerHTML = \"Ошибка\";\r\n"
"               } else if (values[0] == \"test_Mail\") {\r\n"
"                   setTimeout(loadParam('get_Message(MAIL_RET)'), 3000);\r\n"
"               }  else if (values[0] == \"test_SMS\") {\r\n"
"                   setTimeout(loadParam('get_Message(SMS_RET)'), 3000);\r\n"
"               } else if (values[0] == \"set_SAVE\") { RESET\r\n"
"                 //alert(values[0].toLowerCase() + \"--\" + values[1]);\r\n"
"                 if (values[1] > 0) {\r\n"
"                     alert(\"Настройки сохранены в EEPROM, записано \" + values[1] +\" байт\" );\r\n"
"                   } else {\r\n"
"                     alert(\"Ошибка записи в EEPROM, код ошибки:\" + values[1] );\r\n"
"                   }\r\n"
"                  }  else if (values[0] == \"RESET\") {\r\n" 
"                      alert(values[1]);\r\n"
"               } else if (values[0].toLowerCase() == \"set_off\" || values[0].toLowerCase() == \"set_on\") {\r\n"
"                 break;\r\n"
"               } else {\r\n"
"                 element=document.getElementById(values[0].toLowerCase()); if(element) {element.value = values[1]; element.innerHTML = values[1];}\r\n"
"                 element2=document.getElementById(values[0].toLowerCase()+\"2\"); if(element2) {element2.value = values[1]; element2.innerHTML = values[1];}\r\n"
"               }\r\n"
"             }\r\n"
"           }\r\n"
"\r\n"
"         }\r\n"
"\r\n"
"\r\n"
"       } // end: if (request.responseText != null)\r\n"
"     } // end: if (request.responseText != null)\r\n"
"   } else if( noretry != true) { console.log(\"request.status: \"+request.status+\" retry load...\"); check_ready = 1; setTimeout(function() { loadParam(paramid); }, 4000); }\r\n"
" }  \r\n"
" }\r\n"
"}\r\n"
"\r\n"
"function clock() {\r\n"
"var d = new Date();\r\n"
"var month_num = d.getMonth()\r\n"
"var day = d.getDate();\r\n"
"var hours = d.getHours();\r\n"
"var minutes = d.getMinutes();\r\n"
"var seconds = d.getSeconds();\r\n"
"\r\n"
"if (day <= 9) day = \"0\" + day;\r\n"
"if (hours <= 9) hours = \"0\" + hours;\r\n"
"if (minutes <= 9) minutes = \"0\" + minutes;\r\n"
"if (seconds <= 9) seconds = \"0\" + seconds;\r\n"
"if (month_num <=9) month_num = \"0\" + month_num;\r\n"
"\r\n"
"get_time = hours + \":\" + minutes + \":\" + seconds;\r\n"
"get_date = day + \".\" + month_num + \".\" + d.getFullYear();\r\n"
"if (document.layers) {\r\n"
" document.layers.get_time.document.write(get_time);\r\n"
" document.layers.get_time.document.close();\r\n"
" document.layers.get_date.document.write(get_date);\r\n"
" document.layers.get_date.document.close();\r\n"
" }\r\n"
"else\r\n"
" {\r\n"
" document.getElementById(\"get_time\").innerHTML = get_time;\r\n"
" document.getElementById(\"get_date\").innerHTML = get_date;\r\n"
" setTimeout(\"clock()\", 1000);\r\n"
" }\r\n"
"}\r\n"
"\r\n"
"function swich(sw)\r\n"
"{\r\n"
"  swichid = document.getElementById(sw);\r\n"
"  if (swichid.checked)\r\n"
"  { \r\n"
"    loadParam(\"set_ON\");\r\n"
"  }\r\n"
"  else \r\n"
"  {\r\n"
"    loadParam(\"set_OFF\");\r\n"
"  }\r\n"
"}\r\n"
"\r\n"
"function unique(arr) {\r\n"
"  var result = [];\r\n"
"\r\n"
"  nextInput:\r\n"
"    for (var i = 0; i < arr.length; i++) {\r\n"
"      var str = arr[i]; // для каждого элемента\r\n"
"      for (var j = 0; j < result.length; j++) { // ищем, был ли он уже?\r\n"
"        if (result[j] == str) continue nextInput; // если да, то следующий\r\n"
"      }\r\n"
"      result.push(str);\r\n"
"    }\r\n"
"\r\n"
"  return result;\r\n"
"}\r\n"
"   window.onload = function() {\r\n"
"     updateParam(\"get_version,get_testMode,get_datetime(TIME),get_datetime(DATE),get_WORK,get_uptime,get_freeRam,get_loadingCPU,get_uptime,get_pEEV(OH),get_MODE,get_error,get_errcode,get_Temp(TOUT),get_Temp(TIN),get_Temp(TEVAING),get_Temp(TEVAOUTG),get_Temp(TCONING),get_Temp(TCONOUTG),get_Temp(TBOILER),get_oHP(WSPIF)\");\r\n"
" };\r\n"
" </script> \r\n"
" <style>\r\n"
"body{font-size: 12px;padding:0;margin:0; font-family: Arial,'Helvetica Neue', Helvetica, sans-serif;  background: -webkit-linear-gradient(top, rgb(87, 129, 158) 0%, rgb(166, 190, 200) 38%, rgb(215, 205, 177) 90%, rgb(176, 161, 150) 100%);background: -o-linear-gradient(top, rgb(87, 129, 158) 0%, rgb(166, 190, 200) 38%, rgb(215, 205, 177) 90%, rgb(176, 161, 150) 100%);background: -ms-linear-gradient(top, rgb(87, 129, 158) 0%, rgb(166, 190, 200) 38%, rgb(215, 205, 177) 90%, rgb(176, 161, 150) 100%);background: -moz-linear-gradient(top, rgb(87, 129, 158) 0%, rgb(166, 190, 200) 38%, rgb(215, 205, 177) 90%, rgb(176, 161, 150) 100%);background: linear-gradient(to bottom, rgb(87, 129, 158) 0%, rgb(166, 190, 200) 38%, rgb(215, 205, 177) 90%, rgb(176, 161, 150) 100%);}    \r\n"
".row2 dd, .row2 dt{float:left;width:48%;margin:0 1%;line-height:2em;min-height:2em;padding: 0; text-align:center;2em;}\r\n"
".row2 dt {font-size:1.5em}\r\n"
".row2 dd {font-size:1.8em}\r\n"
".row2 dl {float:left; margin: 0; padding:20px 0; list-style:none;  min-height:100px; background: rgba(255, 255, 255, 0.6) center 15px no-repeat} \r\n"
".dateinfo,.row2{display:block;float:left;width:48%; margin:1%; text-align: center;}\r\n"
".dateinfo span{width:48%;display:inline-block;padding:0 1%}\r\n"
".dateinfo span:nth-child(2n){text-align: left}\r\n"
".dateinfo h1, .dateinfo h2{margin:0;padding: 0 0 5px 0;text-align: center;}\r\n"
".onoffswitch { position: relative; width: 60px; display: inline-block; -webkit-user-select:none; -moz-user-select:none; -ms-user-select: none;}\r\n"
".onoffswitch-checkbox { display: none;}\r\n"
".onoffswitch-label { display: block; overflow: hidden; cursor: pointer; border-radius: 20px;}\r\n"
".onoffswitch-inner { display: block; width: 200%; margin-left: -100%; transition: margin 0.3s ease-in 0s;}\r\n"
".onoffswitch-inner:before, .onoffswitch-inner:after { display: block; float: left; width: 50%; height: 26px; padding: 0; line-height: 26px; font-size: 18px; color: white; font-family: Trebuchet, Arial, sans-serif; font-weight: bold; box-sizing: border-box;}\r\n"
"\r\n"
".onoffswitch-inner:after { content: \"X\"; padding-right: 10px; background-color: #FFFFFF; color: #F44E4E; text-align: right;}\r\n"
".onoffswitch-switch { display: block; width: 22px; margin: 0px; background: #F44E4E; position: absolute; top: 0; bottom: 0; right: 33px; border: 2px solid #FFFFFF; border-radius: 20px; transition: all 0.3s ease-in 0s; }\r\n"
".onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-inner { margin-left: 0;}\r\n"
".onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-switch { right: 0px; background-color: #81D14E; }\r\n"
"@media screen and (max-width: 600px) { .dateinfo,.row2{width:98%} }\r\n"
" </style>\r\n"
"</head>\r\n"
"<body> \r\n"
"<div class=\"row2\">\r\n"
" <dl>\r\n"
"     <dt>Тепловой насос</dt>\r\n"
"     <dd>\r\n"
"       <div class=\"onoffswitch\">\r\n"
"         <input type=\"checkbox\" name=\"onoffswitch\" class=\"onoffswitch-checkbox\" id=\"onoffswitch\" onchange=\"swich('onoffswitch')\">\r\n"
"         <label class=\"onoffswitch-label\" for=\"onoffswitch\">\r\n"
"           <span class=\"onoffswitch-inner\"></span>\r\n"
"           <span class=\"onoffswitch-switch\"></span>\r\n"
"         </label>\r\n"
"       </div>\r\n"
"     </dd>\r\n"
"     <dt>Режим работы</dt><dd><span id=\"get_mode\">-</span></dd>\r\n"
"     <dt>Показатели</dt><dd><span id=\"get_errcode\">-</span></dd>   \r\n"
"     <dt>На улице</dt><dd><span id=\"get_temp-tout\">-</span> &deg;C</dd>\r\n"
"     <dt>Из геоконтура</dt><dd><span id=\"get_temp-tevaing\">-</span> &deg;C</dd>\r\n"
"     <dt>Подача СО</dt><dd><span id=\"get_temp-tconoutg\">-</span> &deg;C</dd>\r\n"
"     <dt>Обратка СО</dt><dd><span id=\"get_temp-tconing\">-</span> &deg;C</dd>\r\n"
"     <dt>Температура бойлера</dt><dd><span id=\"get_temp-tboiler\">-</span> &deg;C</dd>\r\n"
" </dl>\r\n"
"</div>\r\n"
"<div class=\"row2\">   \r\n"
" <dl>\r\n"
"\r\n"
"\r\n"
"   <dt>Дата/Время:</dt><dd><span id=\"get_datetime-date3\"></span> <span id=\"get_datetime-time3\"></span></dd>"
"   <dt>Версия ПО:</dt><dd id=\"get_version\">-</dd>"
"   <dt>FREE RAM:</dt><dd id=\"get_freeram\">-</dd>\r\n"
"   <dt>CPU LOAD:</dt><dd id=\"get_loadingcpu\">-</dd>\r\n"
"   <dt>Uptime:</dt><dd id=\"get_uptime\">0m</dd>\r\n"
"   <dt>Режим:</dt><dd id=\"get_testmode2\">-</dd>\r\n"
"   <dt>Перегрев:</dt><dd id=\"get_peev-oh\">-</dd>\r\n"
"   <dd style=\"width:98%;\">\r\n"
"   <span id=\"get_error\" style=\"font-size:1em;line-height:1.3em\" ></span><br/>\r\n"
"<span style=\"font-size:0.8em;font-style:italic;line-height:1em\">Показана упрощенная версия WEB-интерфейса. Проверьте носитель данных и перезагрузите контроллер.<br>"
"Расположение файлов веб-сервера на SPI Flash <input type='checkbox' id='get_ohp-wspif' onChange='setParam(\"get_oHP(WSPIF)\");'><br>"
"<input style=\"margin-top:15px;\" type=\"submit\" value=\"Сброс контроллера\" onclick='loadParam(\"RESET_DUE\")'><a href=\"/journal.txt\" download=\"\"><button>Загрузить журнал</button></a></span>"
"   </dd> \r\n"
" </dl> \r\n"
"</div> \r\n"
"</body>\r\n"
"</html>\r\n";

#endif
